# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-14.04"
  config.vm.hostname = "centos.lab1"
  config.vm.network :public_network, ip: "192.168.1.111"
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../../configureHost_playbook.yml"
    ansible.limit = "all"
    ansible.verbose = "v"
    ansible.inventory_path = "./hosts"
  end
  config.vm.provider "virtualbox" do |vb|
        vb.customize ['modifyvm', :id, '--memory', '1024']
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
end
